name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main
      - OIDC
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: read

env:
  APP_SERVICE_NAME: '12fa-murooka' # Azure Web Appsのリソース名を入れてください
  ACCOUNT_NAME: 's-murooka' # GitHubのアカウント名を入れてください

jobs:
  # .NET8 Webアプリのビルド
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './TFApp_before'

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      # プロジェクトビルド時にパッケージリストアする必要があるため、NuGetソースにGitHub Packagesを追加します
      - name: Nuget add source for GitHub Packages
        run: dotnet nuget add source --username ${{ env.ACCOUNT_NAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.ACCOUNT_NAME }}/index.json"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  # AzureWeb Appsへのデプロイ
  deploy:
    runs-on: ubuntu-latest
    needs: build
 # このenvironmentの設定がエラーを生じさせている可能性があるので、Federated credentialsのsubjectをrepo:s-murooka/hol-12factor-dotnet:environment:productionに変更
 # EntraIDに登録したアプリに対して、共同作成者権限を与えなければazure/login@v1でエラーが発生する？
 # →元に戻して、エラーメッセージの記録だけ行なって、この手順を諦める

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Debug OIDC Token
        run: |
          echo "Retrieving OIDC token..."
          OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange")
          echo "OIDC Token: $OIDC_TOKEN"
        
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.APP_SERVICE_NAME }}
          package: .

      - name: logout
        run: |
          az logout